/**
 * StatsBomb open-data provider. Loads the precomputed, full shot-level dataset
 * (real xG + coordinates, pressures, carries) generated by
 * `scripts/fetch-statsbomb.mjs`. Free and real — covers a historical World Cup
 * (2022 by default). This is the highest-fidelity source: every analytics
 * surface, including shot maps, runs on real data.
 *
 * Run `npm run data:statsbomb` to (re)generate the cache.
 */

import type { DatasetSnapshot } from '@/domain/types';

export async function loadStatsBombSnapshot(): Promise<DatasetSnapshot> {
  // Dynamic import so the 1.2 MB dataset is only bundled/loaded when selected.
  const mod = await import('@/data/cache/statsbomb.json');
  const snap = ((mod as { default?: unknown }).default ?? mod) as unknown as DatasetSnapshot;
  if (!snap.meta) {
    snap.meta = { source: 'statsbomb-open-data', hasAdvancedMetrics: true, hasShotData: true };
  }
  return snap;
}
